export default [
  {
    "favoriteFlag": "0",
    "children": [
      {
        "favoriteFlag": "0",
        "menuId": "101011",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "人员信息管理",
        "menuUrl": "/admin-basic/views/user/UserInfoManager.vue",
        "parentMenu": "101010",
        "prevMenu": "",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "人员信息管理",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "1",
        "menuId": "101009",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "机构信息管理",
        "menuUrl": "/admin-basic/views/user/OrgInfoManager.vue",
        "parentMenu": "101010",
        "prevMenu": "101011",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "机构信息管理",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "0",
        "menuId": "101004",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "角色信息管理",
        "menuUrl": "/admin-basic/views/user/RoleInfoManager.vue",
        "parentMenu": "101010",
        "prevMenu": "101009",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "角色信息管理",
        "permissionAlias": ""
      }
    ],
    "menuId": "101010",
    "menuStatus": "0",
    "menuType": "0",
    "menuName": "人员管理",
    "menuUrl": "",
    "parentMenu": "",
    "prevMenu": "",
    "menuIcon": "kui-icon-member",
    "loadType": "0",
    "rightFlag": "",
    "remark": "",
    "permissionAlias": ""
  },
  {
    "favoriteFlag": "0",
    "children": [
      {
        "favoriteFlag": "0",
        "menuId": "101006",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "系统参数管理",
        "menuUrl": "/admin-basic/views/param/Param.vue",
        "parentMenu": "101005",
        "prevMenu": "",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "0",
        "menuId": "101007",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "系统数据字典",
        "menuUrl": "/admin-basic/views/param/Dict.vue",
        "parentMenu": "101005",
        "prevMenu": "101006",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "0",
        "menuId": "101008",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "系统菜单管理",
        "menuUrl": "/admin-basic/views/param/MenuManager.vue",
        "parentMenu": "101005",
        "prevMenu": "101007",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      }
    ],
    "menuId": "101005",
    "menuStatus": "0",
    "menuType": "0",
    "menuName": "参数管理",
    "menuUrl": "",
    "parentMenu": "",
    "prevMenu": "101010",
    "menuIcon": "kui-icon-operation",
    "loadType": "0",
    "rightFlag": "",
    "remark": "",
    "permissionAlias": ""
  },
  {
    "favoriteFlag": "0",
    "children": [
      {
        "favoriteFlag": "0",
        "menuId": "10100301",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "节假日管理",
        "menuUrl": "/admin-basic/views/setting/DateManage.vue",
        "parentMenu": "101003",
        "prevMenu": "",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "0",
        "menuId": "10100302",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "在线用户",
        "menuUrl": "/admin-basic/views/setting/OnlineUser.vue",
        "parentMenu": "101003",
        "prevMenu": "10100301",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      },
      {
        "favoriteFlag": "0",
        "menuId": "10100303",
        "menuStatus": "0",
        "menuType": "0",
        "menuName": "密码策略",
        "menuUrl": "/admin-basic/views/setting/PasswordStrategy.vue",
        "parentMenu": "101003",
        "prevMenu": "10100302",
        "menuIcon": "",
        "loadType": "0",
        "rightFlag": "",
        "remark": "",
        "permissionAlias": ""
      }
    ],
    "menuId": "101003",
    "menuStatus": "0",
    "menuType": "0",
    "menuName": "系统设置",
    "menuUrl": "",
    "parentMenu": "",
    "prevMenu": "101005",
    "menuIcon": "kui-icon-setting",
    "loadType": "0",
    "rightFlag": "",
    "remark": "",
    "permissionAlias": ""
  }
];
